parameters:
  secret: __SECRET_KEY__
  database_version: '8.0'
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: ~
  database_name: __DB_NAME__
  database_user: __DB_USER__
  database_password: __DB_PWD__
