#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# If you need to, you can define custom settings
# (or remove this section entirely if not relevant for you)
ynh_app_setting_set --key=php_upload_max_filesize --value=1G
secret_key=$(ynh_string_random --length=24)
email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."


# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"
ynh_safe_rm  --recursive "$install_dir/config/parameters.yml.dist"
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="parameters.yml.dist" --destination="$install_dir/config/parameters.yml.dist"
ynh_config_add --template="parameters.yml" --destination="$install_dir/config/parameters.yml"



#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ynh_script_progression "Adding $app's configuration files..."


#=================================================
# SYSTEM CONFIGURATION
#=================================================

pushd "$install_dir"


# ynh_composer_exec install --no-dev

ynh_composer_exec install --no-dev --optimize-autoloader
npm install --legacy-peer-deps
cat "$install_dir/config/parameters.yml"
npm run webpack
APP_ENV=prod php bin/console claroline:install -vvv

php bin/console claroline:user:create $admin $admin $admin $password $email -a

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd


yunohost service add "$app" --description="Claroline LMS" --log="/var/log/$app/$app.log"

chown -R "$app:www-data" "$install_dir"

popd 

ynh_config_add_phpfpm 

# Use logrotate to manage application logfile(s)
# ynh_config_add_logrotate

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
